import type { Metadata } from "next";
import "./globals.css";
import CartList from "@/Components/CartList/CartList";
import { AuthProvider } from "@/context/AuthContext";
import {  CartContextProvider } from "@/context/CartContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
      <meta name="enamad" content="71822216" /> 
      </head>
      <body>
      <AuthProvider>
        <CartContextProvider>
          
        {children}
        <CartList/>
        
        </CartContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
