import type { Metadata } from "next";
import "./globals.css";
import CartList from "@/Components/CartList/CartList";
import { AuthProvider } from "@/context/AuthContext";
import { CartContextProvider } from "@/context/CartContext";
import { Providers } from "./providers"; // اضافه کن

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <meta name="enamad" content="71822216" />
        <meta name="google-site-verification" content="lcbIj7Pc3iCk1eUNo30JTPxosQSo_Cg0tAD2G6xkOeE" />
      </head>
      <body>
        <AuthProvider>
          <CartContextProvider>
            <Providers> {/* این رو اضافه کن */}
              {children}
              <CartList />
            </Providers> {/* این رو اضافه کن */}
          </CartContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}